spring:
  application:
      name: Library
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=library;trustServerCertificate=true;characterEncoding=UTF-8;useUnicode=true;encrypt=true
    username: spring
    password: 12345678
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none  # Use 'validate' or 'none' with Liquibase
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
